CREATE SCHEMA flyway;

CREATE USER analyz_corp_flyway WITH PASSWORD '${ANALYZ_CORP_FLYWAY_PASS}';

GRANT ALL PRIVILEGES ON SCHEMA flyway TO analyz_corp_flyway;

REVOKE ALL PRIVILEGES ON SCHEMA flyway FROM PUBLIC;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA flyway TO analyz_corp_flyway;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA flyway TO analyz_corp_flyway;

ALTER DEFAULT PRIVILEGES IN SCHEMA flyway GRANT ALL PRIVILEGES ON TABLES TO analyz_corp_flyway;
ALTER DEFAULT PRIVILEGES IN SCHEMA flyway GRANT ALL PRIVILEGES ON SEQUENCES TO analyz_corp_flyway;
