services:
  analyz_corp_db:
    image: postgres:17
    container_name: analyz_corp_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSRGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
