INSERT INTO personal_economy.category(name, created_at, created_by, updated_at, updated_by)
VALUES ('Hipoteca', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Seguros', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Comunidad', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Impuestos', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Luz', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Gas', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Agua', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Telefono', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Comida', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Coche', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Seguro coche', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Gasolina', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Hogar', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Osmosis', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Restaurantes', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Gastos Varios', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Viajes', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Regalos', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Spotify', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Ocio', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Amazon', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Gimnasio', now(), 'SYSTEM', now(), 'SYSTEM'),
       ('Centimo Solidario', now(), 'SYSTEM', now(), 'SYSTEM');
